blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/im-anishraj/code-to-git/discussions
    about: Ask questions, share ideas, or get help from the community
